[project]
name = "kinmokusei-cli"
version = "0.1.0"
go-module = "github.com/puffball1567/kinmokusei-cli"
go-version = "1.23"

[package]
entry = "cli.km"
min-kinmokusei = "0.4.1"
backend = "go"
license = "Apache-2.0"

[target]
cgo = "disabled"
